# Thesis Checklist


Students who wish to pursue the thesis option are required to meet with Dr. Bedics at the end of every semester in order to review their progress according to the following timeline. 
Students who miss any of the following steps are removed from the thesis option and will be required to complete the comprehensive exam.  


|| Task           | Date Due | Year | Finished | 
|--|----------------|---------------|------|-----------|
|1.| Thesis Topic Approved | October 1st | First Year | [_____] |
|2.| Setup OSF | October 1st | First Year | [_____] |
|3.| Literature Review Draft Psych 564 | December 15th | First Year | [_____] |
|4.| Academic Good Standing | December 15th | First Year | [_____]  |
|5.| Method Section Draft | May 1st | First Year | [_____]  |
|6.| Literature Review Revision | May 1st  | First Year | [_____]  |
|7.| Academic Good Standing | May 15th | First Year | [_____]  |
|8.| Committee Assignment | June 30th | Summer | [__] Chair<br/>[__] Reader |
|9.| Academic Good Standing | July 3rd | Summer | [_____]  |
|10.| Enroll in PSYC 565 | August 1st | Second Year | [_____]  |
|11.| Committee Approval of Proposal | October 1st  | Second Year | [_____] |
|12.| IRB Submitted | November 1st | Second Year | [_____] |
|13.| Academic Good Standing | December 15th | Second Year | [_____]  |
|14.| Enroll in PSYC 566 | December 15th | Second Year | [_____]  |
|15.| Complete Draft to Dr. Bedics | May 1st  | Second Year | [_____] |
|16.| Committee Approval of Final | May 10th  | Second Year |  [__] Chair<br/>[__] Reader |
|17.| OSF Approval | May 1st | Second Year  | [_____]  |
|18. | Thesis Commons | May 15th | Second Year | [_____]  |
|19. | Thesis Binding | Optional | Second Year | [_____]  |
|20.| GitHub Blog | Optional |Second Year | [_____]  |
|21.| Shiny App | Optional |Second Year | [_____]  |


## Thesis Topic

___

**Defining the Problem Area**

The general thesis topic is required to be selected during the beginning of the first semester of the first year.  The thesis topic, does not, however, determine the hypotheses, methodology or general approach taken by the student to understand the problem (e.g. experimental, quasi-experimental, meta-analytic methods). It would be premature for a student to define a hypothesis in the first year when their understanding of the topic area is just beginning.  Hypotheses are typically developed after the first year of study. 

**Due**: October 1st, First Year

___


## Open Science Framework

**Creating a transparent and reproducible workflow**

[OSF](https://osf.io/) is repository that allows you to transparenlty share your work with the larger scientific community. During the course of the program, you will be using the OSF to organize your thesis and other independent research projects.  Instructions for setting up an OSF project can be found [here](https://speakerdeck.com/jdbedics/osf-setup-and-class-project-introduction) and will be reviewed with Dr. Bedics at your first advising meeting. 

**Due**: October 1st, First Year

___


## Literature Review

___

**Understanding the Problem**

The development of the literature review begins during the fall of the first year during PSYC 564 Advanced Research Methods.  The literature review will become the "introduction" section of the final thesis paper.  The literature review demonstrates the student's mastery of the literature surrounding the *problem* to be addressed by the thesis.  

Initial drafts, such as that from PSYC 564, are 10-12 pages in length.  The development of the literature review is, however, ongoing throughout the two years of the program until the final draft is submitted on May 1st of the second year. 

The typical length of a *complete* literature review is between **20-40 pages** long but there is no maximum length. 

**Due**: December 15th, First year (First Major Draft); May 15th, end of first year (Second Major Draft); May 1st, end of second year (Final Draft)

___


## Method Section

___

**Solving the Problem**

The method sections defines the procedures of the thesis. The method section consists of the participant selection, selection of methods of measurements or materials, and the procedure.  The method section can be worked on in PSYC 552 Psychometrics during spring of the first year and is finalized during PSYC 565 in the fall of the second year.

**Due**: May 1st, First Year (First Draft)

___

## Committee Assignment

___

Committee members are faculty or experts in the field that support the students work on the thesis. Students work with the program director to find the most appropriate committee members to support their research project.  

Please see the **Thesis Committee** section of this handbook.
  
**Due**: June 30th, Summer after First Year

___

## Committee Approval of Proposal

___

During the summer following the first year, committee members read the literature review and method section and provide a general statement of approval to Dr. Bedics.  Based upon this approval, students are allowed to progress to the *thesis track.*  The rest of the thesis process is guided through coursework including PSYC 565 Research Practicum in the fall of the second year and PSYC 566 Thesis in the spring of the second year. 

**Due**: October 1st, Second Year

___

## Academic Good Standing

___

Academic good standing refers to maintaining a GPA above a 3.0 throughout the entire program and acting consistently with all policies and procedures defined by the program (see Program Handbook) and university (see university policy and procedures).  Any student who receives below a B- in any course is not allowed to complete the thesis for course credit and partial fulfillment of the degree. 

**Due**: Every semester

___



