# Thesis Committee

 
**Committee Membership**

The committee is composed of a Chairperson and one other members, one of whom must be a full-time faculty member from the student’s department or school. The requirements for each are listed below:

___

**Committee Chair**
The chair must have knowledge of the area under investigation for the project or thesis. Must be a part- or-full-time faculty member of the department or school. Must be chosen with the approval of the Program Director, Dr. Bedics.

**Committee Reader**
Members must have knowledge of the area under investigation for the project or thesis. Must be full- time, part-time faculty, or a professional in the community with at least a Master’s degree. He or she must be chosen with approval of program advisor and thesis Committee Chair. 

___


## How to get a committee:

For many faculty, being on a thesis committee is a lot of work with little payoff.   Consequently, it can be a challenge to find faculty to support your research project. How you approach faculty is critical. Please contact Dr. Bedics before reaching out to prospective committee members.

1.	Identifying potential faculty – Search the CLU website for potential faculty that could contribute to your idea.  Look at faculty interests in graduate psychology, undergraduate psychology, as well as other departments at CLU.  You could also identify faculty at other universities that might serve on the committee. 

2.	Foot-in-the-door – Introduce yourself to faculty through email.  Do not ask them to join your committee.  Instead, ask them if they have time to answer questions about your project. The point here is that if they are not willing to give you any feedback then they will never be willing to be on your committee.  The foot-in-the-door strategy allows you to get some feedback even if they are not willing to be on your committee.  Here is an example email:

```
Dear Dr. ###,

My name is STUDENT and I am currently developing my master’s thesis project at California Lutheran University.  The topic is on <TOPIC>. I think your expertise in <AREA> would help me in thinking through some of the details of my project.  I was curious if you could make time to answer a few questions over email or perhaps even chat over the phone.  I appreciate your time and will be as concise as possible.  I have attached a brief summary of my project.

Thank you for your time and consideration.

Sincerely,

First Last Name
```

3.	Requesting committee membership – At some point you will have to ask faculty to join your committee.  It is best to let the director make this request.  The director can email the potential committee member and discuss the role of the chair and reader as well as compensation for their time. The following information is often communicated to the potential committee members:

## Working with your committee

The committee will be most successful if you establish clear expectations of when you will talk or email with each other.  Clearly established expectations will prevent you from emailing too little or too much. Establish the following:
  
  * Make a clear statment that you would like to be mindful of their time and not approach them too much nor too little.
  
  * How often would they like to look at your work?
  
  * How often would they like to talk/video conference?
  












