# Coursework Relevant to the Thesis

___

The knowledge gained from every course taken at CLU can be used to improve the development of the thesis or research project. For example, if you have an interest in a specific disorder then it makes sense that you study that disorder in *PSYC 510 Psychopathology*.   In *PSYC 560 Statistics I: Exploratory Data Analysis*, you might consider finding open data that allows you to better understand your problem area using method of data visualization.    

There are, however, specific courses where the thesis is explicitly incorporated into course assignments. The following are the MSCP courses that explicitly incorporate elements of the thesis into the syllabi: 

|PSYC#| Course           | Semester | Year | Task | 
|--|----------------|---------------|------|-----------|
| 564 | Adv. Research Methods | Fall | One | Start Lit Review; Start References |
| 562 | Statistics II: Regression | Spring | One | Data Analytic Plan |
| 552 | Psychometrics | Spring | One | Method |
| 521 | Ethics | Summer | One | Pre-Registration |
| 565 | Research Practicum | Fall | Two | IRB, Intro, Method |
| 566 | Thesis| Spring | Two | Complete Draft due May 1st |
| 599 | Thesis Continuation| Every semester Post 2nd year | Two+ | Every semester until the thesis is complete |


**PSYC 564 Advanced Research Methods**

In PSYC 564, students develop the beginning of the literature review and begin to master the 7th edition of the Publication Manual of the American Psychological Association.

___

**PSYC 562: Statistics II: Regression**

In this course, students learn the basics of statistical modeling with an emphasis on regression.  Although the focus of the course is on regression, students can work with the instructor to consider models that might address their research hypotheses.  If students have a published article that closely approximates the study they want to run then students might learn more about the analyses conducted in that article.  

___

**PSYC 552: Psychometrics**

The emphasis in this course is psychometric theory which includes an understanding of the concepts of reliability and validity.  Students can use this course to examining the psychometric properties of the most likely methods of measurement they will use in their research such as specific self-report questionnaires. 


___

**PSYC 521: Clinical and Research Ethics**

In this course, students learn about the concept of open science which includes reproducibility, transparency, and pre-registration. Students continue to develop their OSF page and learn how to pre-register their hypotheses. 

___


**PSYC 565: Research Practicum**

In addition to finishing up their introduction and method sections, students main task is to complete the CLU IRB, [https://www.callutheran.edu/research/irb/](https://www.callutheran.edu/research/irb/).  The IRB process is very extensive and students are required to complete an online ethical training. Once the IRB is successfully passed, students can collect their data.  The process of getting IRB approval can be a  lengthy one and require several revisions.  Students submit their IRB in collaboration with their Committee Chair who will submit the IRB proposal to the IRB committee on the student's behalf. 

___

**PSYC 566: Thesis**

During this semester, students work independently on their thesis (with their committee members) and complete their results and discussion sections.  The semester requires the student to structure their own time as there are no formal class meetings.  Students are often collecting data during this final semester. 

In order to pass PSYC 566, students are required to have a complete draft of their thesis that is approved by the chair, reader, and program director by **May 1st**.  Students often do not complete the thesis for a variety of reasons including an inability to collect data, medical and health problems, or other life priorities.  In these circumstances, students have two options:

  ***1. Continue the thesis*** - Students can choose to continue the thesis and enroll in PSYC 599 (see next section), and pay the associated fee for every semester until the thesis is complete.  Students are assigned the following grade of "IP" for PSYC 566 until the thesis is approved:
  
  * **“IP” (In Progress)** is given for theses, practica, internships and courses wherein the work has been evaluated and found to be satisfactory to date, but the assignment of a grade must await its completion. “IP” carries no credit until replaced by a permanent grade. The “IP” grade may be replaced by the appropriate final letter grade within one calendar year from the start of the class. “IP” grades which have not been resolved will be changed to “F” (undergraduate) or “NC” (graduate) at the time the student’s degree is posted.

  ***2. Drop the Thesis and take the Comprehensive Exam*** - Students can register for the comprehensive exam and pay the associated fee.  The comprehensive exam is offered every semester and should be taken the first semester the student does not register for PSYC 599. 

___

**PSYC 599: Thesis Continuation**

Students who do not complete the thesis by the end of their second year and choose to continue to work on thesis must register for *PSYC 599: Thesis Continuation* every semester until the thesis is approved by the committee members and Program Director. 

___







