# Guidelines and Procedures

Successful completion of the thesis requires students to remain in good standing in accordance with the the guidelines regarding academic success and integrity set forth in the university’s Graduate Catalog and the MS Clinical Psychology Student Handbook.

___

**Integrity**

Academic dishonesty diminishes the quality of scholarship and defrauds those who depend upon the integrity of the educational system. Consult the CLU Graduate Catalog for definitions of cheating, fabrication, facilitating academic dishonesty, and plagiarism. According to university policy, students who engage in academic dishonesty may be in jeopardy of disciplinary action, including suspension or expulsion from the university.

___

**Failure to Complete the Thesis**

Many students are unable to complete the thesis within the expected two years of study.  Students who do not successfully complete the thesis within the first two years are required to maintain **continuous enrollment** by registering for *PSYC 599C-01 Thesis Continuation* **every semester** until the thesis is successfully completed. 

Under special circumstances, students can take a leave of absence from the university.  Such a leave of absence is completed in accordance with university policies which can be found through the university [registrar](https://www.callutheran.edu/students/registrar/).



___



