--- 
title: "CLU MS Clinical Psychology Thesis Handbook"
author: "Jamie Bedics, PhD, ABPP"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
classoption: openany
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
github-repo: jdbedics/thesishandbook
description: "Guidelines for completion of the thesis for the MS in Clinical Psychology Program at CLU."
---

# Goal of the Handbook

___

The goal of this handbook is to provide students with the information needed to successfully complete the master's thesis in the MS in Clinical Psychology Program (MSCP) at California Lutheran University (CLU).  The manual should be understood as a supplement to the broader policies and procedures defined by the program and university. 

___

## Scholarly Research

___

Scholarly research requires the skills of inquiry which must be demonstrated by all students. As a participant in research activities at CLU, the University expects you to develop the abilities to:

  1. Create or contribute empirical knowledge to the existing body of information in a discipline;
  2. Carryout systematic inquiry;
  3. Use tools of research including analyzing existing research, implementing research designs, using and/or developing instrumentation, employing appropriate methods of data analysis, and handling the logistics of conducting a research study;
  4. Work with faculty or other professionals on a research project;
  5. Use scholarly writing techniques.

Research may be a thesis or a research project. While both are important contributions to the body of knowledge in a discipline, they have different purposes as described in the following sections.

___

## Comprehensive Exam


By default, students entering the MSCP program are required to complete the comprehensive exam.  Students can, however, choose to _opt out_ of the comprehensive exam and instead complete a thesis.

**What is the comprehensive exam?**

  * A closed book essay test that covers all the material studied during the course 
      of the MSCP program.  
  * The test is offered at the end of the spring semester during the second year. 
  * The exam consists of a morning session (9AM-Noon) and an afternoon session (1PM-4PM).
  * During each session, students choose to respond to 3 of 5 questions.
  * Instead of credit, students register for the exam by paying a comprehensive exam *fee* 
    during the semester they take the exam (typically spring of their 2nd year).
  * Students who take the comprehensive exam are **not** required to take PSYC 565, 
    Research Practicum, in the fall of their 2nd year.  Instead, they can choose an 
    elective of their choosing which could be PSYC 565 if they choose. 
  * Students **do not** take PSYC 566, Thesis, in the spring of their 2nd year.  As a 
    result, students who take the comprehensive exams graduate with a total of 37-units 
    instead of 40-units with the thesis option.
  

___

## Thesis

The thesis is the result of an original empirical investigation that creates new knowledge within a discipline. It solves a problem related to lack of knowledge and is generally composed of the following elements:

  1. Identification of a problem caused by lack of knowledge;
  2. Background and literature review of existing information about the problem; 
  3. Methods to be used for obtaining the needed knowledge;
  4. Resulting new knowledge;
  5. Interpretation of the new knowledge.
  6. Transparent and open sharing of materials and results via pre-registration and the open science framework 

**Tasks:**

  * Students complete all the requirements outlined in this manual.
  * Students enroll in *PSYC 565 Research Practicum* during the fall of their 2nd year.
  * Students enroll in *PSYC 566 Thesis* during the spring of their 2nd year.

___

## Pros and Cons: Thesis Vs. Comps

*Thesis "Pros"*
  
  * Students gain a high degree of expertise and mastery in the area under study.
  * The thesis timeline creates accountability and structure in completing the thesis.
  * Doctoral programs often look favorably towards a completed thesis that demonstrates students' ability to successfully complete a research project.
  * Doctoral programs that require a thesis might *waive* the thesis requirement based upon the completed thesis at CLU.
  * Students can have the thesis bound into a book (see Thesis Binding).
  * Students can earn quality letters for recommendation from their thesis committee members. These letters are often more meaningful than letters from employers or course instructors. 

*Thesis "Cons"*
  
  * Despite the structure offered through coursework, the thesis requires a considerable amount of extra work and self-discipline. The amount of autonomy can be quite stressful.
  * Students take an extra 3-units (PSYC 566) in the spring of their 2nd year for a total of 40-units versus 37-units for the comprehensive exam option. 

___

  
*Comps "Pros"*
  
  * Students are given a review sheet to help direct their effort to study.
  * The exam is completed in a day as compared to the thesis that takes 2-years.
  * Questions that are not adequately answered can be successfully remitted before "failing."
  * The pressure to meet thesis requirements, every semester, is removed.
  * Students can still complete an **research project** (see next section) which would allow the first three *thesis pros* to be achieved.
  * Students choose a 3-credit elective during their second year.
  * The entire program is 37-units versus 40-units with the thesis option.
  
*Comps "Cons"*
 
  * A 6-hour, closed book, essay test can be stressful and exhausting.
  * Research experience is valued by PHD programs and many, but not all, PSYD programs.
  * The research project, if chosen, could not be as structured as the thesis option.
  
___

## Research Project Option

**Research Project + Comprehensive Exam** 

Students can complete their own independent research project, identical to the thesis, but without the coursework (PSYC 565 & PSCY 566).  There are two scenarios where this can occur:

  1. A student can decide, from the beginning of the program, that they want to avoid the pressure and extra work of the thesis requirements but use the program to work on an research project.  They could take PSYC 565 in the fall of their second year but will not take PSYC 566 during the spring.
  
  2. Students might attempt the thesis but, for a variety of reasons, fall behind and not be able to complete all the necessary requirements of the thesis in order to graduate. If this occurs, then the student can always move to the comprehensive exam while continuing to work on their thesis as an independent research project.  
    
In both of these scenarios, students are required to take the comprehensive exam and pay the comprehensive exam fee, in order to graduate and in in accordance with univesity policies which can be found through the [university registrar](https://www.callutheran.edu/students/registrar/).  

___

